baseURL = "https://kankov.me/"
languageCode = "en-us"
title = "Alexey Kankov"
theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Alexey Kankov"
    description = "Personal blog/portfolio"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["php", "sql", "javaScript", "python"]

# [[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1

# [[menu.main]]
#     url = "/about/"
#     name = "About"
#     weight = 2

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 3

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "fas fa-envelope"
#     weight = 1

[[menu.icon]]
    url = "https://github.com/akankov/"
    name = "fab fa-github"
    weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "fab fa-twitter"
#     weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/akankov/"
    name = "fab fa-linkedin"
    weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "fab fa-stack-overflow"
#     weight = 5
